# Enter here your API KEY from https://home.openweathermap.org/api_keys
APIKey: ENTER_YOUR_API_KEY_HERE

# Enter here city for each you want weather to be.
cityName: "Warsaw"

# Enter the ISO 3166-1 country code. For example Poland has 'pl' ISO code.
countryCode: "pl"

# Optional, if you are living in US, otherwise set to ''
stateCode: ""

# If you want the weather to be the same as real in provided City type 'true' here.
realTimeWeather: true

# If you want the time to be the same as real in provided City type 'true' here.
realTime: true
